ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../java]
ifdef::backend-pdf[:imagesdir: {outdir}/{imagesdir}]

== Introducción

=== Sección 0

hola mundo asdas d

[plantuml,casos-de-uso-crud,png]
....
left to right direction
skinparam packageStyle rect
title Productos y lugares

actor Usuario as usuario

rectangle red{
    usuario -- (lugares)
    (lugares) <.. (alta lugar) : extend
    (lugares) <.. (modificacion lugar) : extend
    (lugares) <.. (ver lugar) : extend

    (productos) ...> (ver lugar)
    usuario -- (productos)
    (productos) <.. (alta producto) : extend
    (productos) <.. (modificacion producto) : extend
}

....

Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas "Letraset", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.


==== Una subsección en este doc

adadasdas
a
sd
as




